### ISSUE TITLE
Feature request: Add Rename to Move Action

### ISSUE THREAD

**Issue by Alexisvt** [alm-tools/alm#103]
Hi @basarat I think will be better to add a `/ Rename ` tag to the `Move file / folder` action.
I know that as you told me before `move` action can be used to `rename` but that is not  clear at the first time. I mean we can think that maybe we can use that for renaming but that can be hard for some (for example me :stuck_out_tongue_closed_eyes: ) So Can you add something else on the `move` action to be more clear?

I'm thinking another label like text like this: **M to move or Rename file / folder**

**Comment by basarat** [comment]
Basically the human difference is "rename is local" "move is move to any other folder OR another place in the same parent folder (effectively rename)". 

If we add an explicit rename : we should truncate the preceding file path and not let you change that.

I'll just do the simple thing of adding another tooltip / kbd shortcut for now 🌹

**Comment by Alexisvt** [comment]
Thanks!! :+1: I didn't think it in that way but I get your point me :smile:

**Comment by basarat** [comment]
Released with `0.0.65` :rose:

<img width="290" alt="screen shot 2016-05-24 at 8 21 02 am" src="https://cloud.githubusercontent.com/assets/874898/15486385/8bb05e24-2188-11e6-8fe3-a4f542189e98.png">
