### ISSUE TITLE
Feature request: a way to detect and show the latest node package in package.json file

### ISSUE THREAD

**Issue by Alexisvt** [alm-tools/alm#104]
Hi @basarat  do you think is possible to add a functionality that shows a tooltip window with the latest number version of that package like this:

![image](https://cloud.githubusercontent.com/assets/7120647/15491565/f0cb2b68-212e-11e6-9780-a25703375c69.png)

**Comment by basarat** [comment]
I plan to do a full sprint on `package.json` support. This can be a small part of it (I have quite a few ideas). But its going to be a while (a month away it seems).

**Comment by Alexisvt** [comment]
:+1:

**Comment by basarat** [comment]
Here you go `0.0.71` :rose: 

![image](https://cloud.githubusercontent.com/assets/874898/15538455/b53991d8-22bf-11e6-8057-612835131862.png)
