### ISSUE TITLE
Feature request: a way to see most common image formats

### ISSUE THREAD

**Issue by Alexisvt** [alm-tools/alm#106]
Hi @basarat Do you think is possible to see images in alm editor?
Currently my project have some images but when I try to open it with alm tool it doesnt understand the image format and show a lot stuft that I dont understand buajaja :smile_cat: 

![image](https://cloud.githubusercontent.com/assets/7120647/15524252/f2d2e3d8-21dd-11e6-8c28-a22362c8296c.png)

**Comment by basarat** [comment]
Right on it. Will try and do it tonight :rose:

**Comment by Alexisvt** [comment]
Thanks man!! you are the best!! :smile_cat:

**Comment by basarat** [comment]
Released with `0.0.68` :rose: 

![viewer](https://cloud.githubusercontent.com/assets/874898/15534559/ab4bfbec-22ac-11e6-8570-63c5c751e4ad.gif)
