### ISSUE TITLE
Feature request: reveal in explorer action for tree view panel

### ISSUE THREAD

**Issue by Alexisvt** [alm-tools/alm#109]
Hi @basarat !! I'm really happy to see how the app is growing for good!! Thanks!!
I want to ask you if there is a way to add a new shortcut on the tree view to view the item in the explorer window.
The behavior will be to press the shortcut and alm tool open a windows that contains that item! :smile_cat:

**Comment by basarat** [comment]
> I want to ask you if there is a way to add a new shortcut on the tree view to view the item in the explorer window.

Sadly not easily possible as the browser window might not be on the machine that contains the server, and only the server can issue such a command to the OS.

**I do however have a shortcut `c` (listed in the help as well) that just copies the path.**

And then its a simple matter of `Win + R` (windows run command) and `ctrl + v` (paste the copied path) and `enter` : Violla you have the explorer open.

Alternatively if its a file path you can open in some other editor (that isn't just for typescript) just as easily :smile: 

Closing as *too complex* for now :rose:

**Comment by basarat** [comment]
I can consider the *remote user* issue later (will have to deal with that at some point anyways). Till then I'd rather implement this for you :rose:

**Comment by basarat** [comment]
Shortcut `o`. Released with `0.0.72` works nicely both on mac / windows  :rose: 

![image](https://cloud.githubusercontent.com/assets/874898/15558890/fd881070-2320-11e6-95d2-26c1e94b4b6b.png)
