### ISSUE TITLE
Virtual Projects

### ISSUE THREAD

**Issue by basarat** [alm-tools/alm#115]
Sometimes you will open a file (JavaScript or TypeScript) and you want typescript intellisence for that file even without a `tsconfig.json`. We can support that by providing a `virtual` project option in the project search that creates a project by standard compilation context expansion from a `.ts` or `.js` file :rose:

**Comment by basarat** [comment]
Released with `0.0.89` Use project search to select a `virtual project` if you have a `.js` file open :rose:

![virtual](https://cloud.githubusercontent.com/assets/874898/15649398/9c750ada-26b4-11e6-994c-d85fa0afc9e7.gif)

**Comment by Alexisvt** [comment]
jejeje love the icon! thanks!!! :D
