### ISSUE TITLE
Move to Monaco

### ISSUE THREAD

**Issue by basarat** [alm-tools/alm#120]
Replace codemirror with monaco. There is absolutely nothing wrong with CodeMirror. Its has been an intense pleasure working with it, the docs are great and the support (Marjin) is awesome :rose: :100: 

## The main reason

If anyone is wanting to create their own IDE around monaco I want alm to be *the* project that they fork from. This is going to be lot of work. 

We rely fairly heavily on CodeMirror https://github.com/alm-tools/alm/tree/master/src/app/codemirror and had to create a few plugins https://github.com/alm-tools/alm/tree/master/src/app/codemirror/addons that will need to be rewritten. This should raise the project to a whole new level ` ¯\_(ツ)_/¯ ` :rose:

**Comment by kataras** [comment]
It's a good choice, Monaco is far better (in my opinion), well done!

**Comment by kataras** [comment]
It's a good choice, Monaco is far better (in my opinion) but when I tried to test it I didn't find any docs except the basic code lines to make it work. Hopes you the bests, well done!

**Comment by kataras** [comment]
It's a good choice, Monaco is far better (in my opinion) but when I tried to test it I didn't find any docs except the basic code lines to make it work. Hope you the bests, well done!

**Comment by Alexisvt** [comment]
Wow!  Just wow! I feel we are closing to something really awesome! Cause
Monaco is indeed the right choice! I will pry for you my friend since it
seems that  there isn't a lot of documentation but I know that you will
handle it 😉! Please do it! 😆😆😆

**Comment by ichpuchtli** [comment]
If anyone could do it it would be you @basarat. You're a wizard.

**Comment by Alexisvt** [comment]
Agree! 🎩👏

**Comment by basarat** [comment]
Released with `0.1.0`. Let me know how it goes. Please raise issues :rose:
