### ISSUE TITLE
doesnt run on windows 

### ISSUE THREAD

**Issue by pdeva** [alm-tools/alm#123]
get this error while starting:
http://screencast.com/t/4CFCnMFh9i2

**Comment by basarat** [comment]
Thanks for trying it out :heart: You need to run it from a project folder please. We should report it as an error :rose: 

Please see https://github.com/alm-tools/alm/issues/122

**Comment by basarat** [comment]
We now report this as an error :rose: `0.3.2`

<img width="830" alt="screen shot 2016-08-05 at 2 18 23 am" src="https://cloud.githubusercontent.com/assets/874898/17409556/2348ce16-5ab3-11e6-8806-8ec46228ca13.png">
