### ISSUE TITLE
Feature request: right click context menu

### ISSUE THREAD

**Issue by styfle** [alm-tools/alm#126]
The right click context menu is currently just the default Chrome menu:

* Back
* Foward
* Reload
* Spellcheck
* Inspect

These are not relevant to an IDE. I would expect to right click on a function name and have a context menu item that says some like Jump To Definition.

**Comment by basarat** [comment]
Thanks for trying and extra thanks for the feedback 🌹 That said we have a command pallete and I try my best not to use the mouse. This will most likely never happen so closing ❤️

**Comment by styfle** [comment]
Are you interested in providing an alternative to [vscode](https://github.com/Microsoft/vscode) or is this more of a pet project?

**Comment by jmls** [comment]
Whilst I appreciate that _you_ do not use a mouse, thousands of developers using an IDE do use a mouse ;) I was looking for a context-menu in the treeview to add/create/remove/rename files, and was surprised not to see one.
