### ISSUE TITLE
Feature request: intellisense on tsconfig json file

### ISSUE THREAD

**Issue by Alexisvt** [alm-tools/alm#134]
Hi @basarat thanks for this amazing editor!! It's getting better and better and more with monaco addition! I have a question, Do you think is possible to have intellisense on tsconfig file? Thanks!

**Comment by Alexisvt** [comment]
And btw I think we lost the intellisense also on package json file too, I know that you are migrating those things, but I want to remind you about it, thanks :smile:

**Comment by basarat** [comment]
Thanks, this feedback is highly appreciated as its not fun *rewriting* features when no ones asked for them so thank you! 👍 

We actually lost more than just the autcomplete in the latest updates : https://github.com/Microsoft/vscode/issues/8172 I'll work on bringing it back :rose:

**Comment by Alexisvt** [comment]
Thanks you are the best!! :)

**Comment by basarat** [comment]
Released with `0.1.9` :rose: 

we now have autocomplete for tsconfig + hover for package.json dependencies sections (which is what we had before monaco). I also added formatting support for all json files cause it was easy to do :)
