### ISSUE TITLE
Do not generate .js on save

### ISSUE THREAD

**Issue by emzero** [alm-tools/alm#135]
Whenever I save a .ts file a .js file is generated next to it. I don't know if it's because of how the tsconfig.json is configured but VSCode is not doing it so I thought is something related to alm.

Just in case my `tsconfig.json` looks like this:
```json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "target": "es6",
    "jsx": "preserve",
    "experimentalDecorators": true,
    "sourceMap": true,
    "skipDefaultLibCheck": true
  }
}
```

**Comment by Alexisvt** [comment]
Yes it's because alm by default will set "compileOnSave" flag to true!, your tsconfig must to looks like:
```json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "target": "es6",
    "jsx": "preserve",
    "experimentalDecorators": true,
    "sourceMap": true,
    "skipDefaultLibCheck": true
  },
"compileOnSave": false
}
```

**Comment by emzero** [comment]
Great, thank you!
