### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Sorceror** [alm-tools/alm#147]
I just found alm project and I'm quite impressed! Pretty much the only one thing that I miss is support for different file type icons similar to https://atom.io/packages/file-icons (and maybe some settings for size of item in tree view..? :) ).

**Comment by basarat** [comment]
That icon set could really use a `.ts` icon :)

**Comment by basarat** [comment]
couldn't find a `.ts` icon here : http://fizzed.com/oss/font-mfizz or here : http://vorillaz.github.io/devicons/#/dafont. If you can point me to a font file that has one for `.ts` I'd be happy to bring it in :rose:

**Comment by Sorceror** [comment]
Isn't it possible to use directly the build font from [file-icons](https://github.com/DanBrooker/file-icons) project? [woff2 file](https://github.com/DanBrooker/file-icons/blob/master/resources/fonts/file-icons-v1.7.17.woff2)

**Comment by basarat** [comment]
> I meant to add support for all other file types not just typescript in general :)..

I get that :heart: Just that I think that woff2 file doesn't have an icon for `.ts` files. So would be bad if a ts ide has icons for everything except a ts file :)

**Comment by Sorceror** [comment]
[file-icons.less](https://github.com/DanBrooker/file-icons/blob/f2231cdbe97507cd4290c0d1b8bebb9e67a214fd/styles/file-icons.less#L2006) which points to [icons.less](https://github.com/DanBrooker/file-icons/blob/591cfef7d135bd1e52b43409adcd0ea2b4f977e3/styles/icons.less#L453) which leads to [custom file-icons family](https://github.com/DanBrooker/file-icons/blob/591cfef7d135bd1e52b43409adcd0ea2b4f977e3/styles/icons.less#L178) and eventually to [file-icons-v1.7.17.woff2 file](https://github.com/DanBrooker/file-icons/blob/be5f52e500f7f474f53e6a00eb7faf11deb26a55/styles/fonts.less#L31).. 
So there is support for TS isn't it?

**Comment by basarat** [comment]
Indeed I see ts in there https://github.com/DanBrooker/file-icons/blob/591cfef7d135bd1e52b43409adcd0ea2b4f977e3/styles/icons.less#L453-L454. I'll add this support :rose:

**Comment by basarat** [comment]
I experimented with the file-icons workflow: https://github.com/basarat/fileicons :heart: Didn't like maintaining 5! font files to chose icons from. Just using font-awesome instead :rose:

**Comment by basarat** [comment]
<img width="207" alt="screen shot 2016-07-16 at 1 09 14 pm" src="https://cloud.githubusercontent.com/assets/874898/16892534/144f8832-4b59-11e6-9f47-a65cc3c07d26.png">

`0.1.24` :rose:
