### ISSUE TITLE
Show method parameters during typing of method call

### ISSUE THREAD

**Issue by Sorceror** [alm-tools/alm#149]
It would be also great if when method call is typed `foo(` then the context popup would not show just the possible values (as it is now) but also what parameters are expected. Something like 
![example](https://d3nmt5vlzunoa1.cloudfront.net/phpstorm/files/2016/06/param-completion.gif)

It might be too complicated, but even bellow implementation would help a lot.

![example](http://i.imgur.com/YFBYdTE.png)

This example is from PhpStorm 2016, but well I just wanted to show the idea, it doesn't have to be the same.

**Comment by basarat** [comment]
We had function signature completion, however after the move to monaco it got *sorted* away from the top of the list. I've added `(sig)` prefix to make sure they show up at the front of the list again :) 

<img width="527" alt="screen shot 2016-07-21 at 8 01 06 am" src="https://cloud.githubusercontent.com/assets/874898/17004701/8b2e9b0a-4f19-11e6-9223-bf42a2d976b4.png">

**Comment by basarat** [comment]
Documented here as well : https://basarat.gitbooks.io/alm/content/features/autocomplete.html#functions (however the screenshots are pre monaco) :rose:

**Comment by basarat** [comment]
`0.1.35` :rose:
