### ISSUE TITLE
alm does not work when external diff/mergetool for git configured

### ISSUE THREAD

**Issue by htammen** [alm-tools/alm#150]
I have defined external diff and merge tools in my .gitconfig. Everytime I open alm it automatically opens my mergetool several times and I cannot work in the editor anymore. When deleting the configuration from .gitconfig alm works fine again.

```
[merge]
	tool = extMerge
[mergetool "extMerge"]
	cmd = extMerge \"$BASE\" \"$LOCAL\" \"$REMOTE\" \"$MERGED\"
[mergetool]
	trustExitCode = false
[diff]
	external = extDiff
[difftool "sourcetree"]
	cmd = /Applications/p4merge.app/Contents/MacOS/p4merge \"$LOCAL\" \"$REMOTE\"
	path = 
[mergetool "sourcetree"]
	cmd = /Applications/p4merge.app/Contents/MacOS/p4merge \"$BASE\" \"$LOCAL\" \"$REMOTE\" \"$MERGED\"
	trustExitCode = true
```

**Comment by basarat** [comment]
> Everytime I open alm it automatically opens my mergetool several times

I don't see how it can happen. Sorry if it is indeed my fault. I have absolutely no clue. Are you sure its alm doing this?

**Comment by htammen** [comment]
Yes, I`m sure. When I delete the gitconfig settings alm is working without problems. 
But I close the ticket now if you have no idea what the reason is. I don't need the settings anymore. Found other ways for diff and merge.

Thx and regards
Helmut

**Comment by basarat** [comment]
Sorry, I realised something that might (obviously) be causing it and fixed it in the attached commit ^. Released it with `0.1.38` :rose:

**Comment by basarat** [comment]
The connection missing in my brain was `opening alm` vs. `opening any file in alm` :)

**Comment by htammen** [comment]
Thx, works fine now. Congratulations for this great typescript editor. Even though I'm using IntelliJ Idea for my larger projects I will give alm a try for smaller projects in the future.
