### ISSUE TITLE
Shortcut "Ctrl + \" not working on Linux + German keyboard

### ISSUE THREAD

**Issue by aravantv** [alm-tools/alm#154]
Under Linux, with a German keyboard, pressing Ctrl+\ does not open the tree view. So that you know, getting this combination on a German keyboard requires pressing Ctrl+AltGr+some normal key ("ß" if you really want to know).

I guess that's quite a corner case but I still signal it cause it's the first command of the quick start (https://basarat.gitbooks.io/alm/content/quickstart.html) and it prevents to go any further :-/

**Comment by esbeto** [comment]
It won't work also on Spanish Keyboards, need to type Command + alt + º

**Comment by aidansteele** [comment]
1Password's primary keyboard shortcut is Cmd+\ so the treeview isn't accessible for 1Password users either. I'm embarrassed to say I'm actually blocked by this!

**Comment by basarat** [comment]
I've let this sit in my brain for quite a while. The key desire is to allow keyboard customization. That is not on the board at the moment :-/

**Comment by basarat** [comment]
One can use the command pallette to trigger the command. However I agree that it will be a painful experience.
