### ISSUE TITLE
Support for new TS 2.0 tsconfig parameters

### ISSUE THREAD

**Issue by Sorceror** [alm-tools/alm#156]
Currently if project `tsconfig.json` file contains new available parameters from TS 2.0 (specifically [noUnusedParameters and noUnusedLocals](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#flag-unused-declarations-with---nounusedparameters-and---nounusedlocals) they're shown as errors and alm is not able to work with the project anymore.

Is TS 2.0 already supported?

**Comment by basarat** [comment]
> Is TS 2.0 already supported?

Yup. But to provide a nice tsconfig validation experience forces us to maintain this code on our side. Its not that hard as you can see from the attached commit. Updated with the latest / greatest options and released with `0.2.1` :rose:
