### ISSUE TITLE
News: An alm package has been added to the Arch User Repository (AUR)

### ISSUE THREAD

**Issue by fusion809** [alm-tools/alm#159]
Hi,

Just wanted to mention that I have added an alm package to the AUR ([link](https://aur.archlinux.org/packages/alm)). I have also added alm to my own binary repository for Arch Linux, `[pkgbuild-current]`, see https://github.com/fusion809/PKGBUILDs/releases/tag/current for details. 

Thanks for your time,
Brenton

**Comment by basarat** [comment]
Thanks for sharing. Hope you find it useful 🌹 ❤️ 😍
