### ISSUE TITLE
Settings UI to change the editor main font

### ISSUE THREAD

**Issue by lennartjansson** [alm-tools/alm#174]
Consolas is great, but I prefer to work in a different font. It's possible to hack around the current font-family constant with browser extensions, but it'd be nice to have first-class support for this setting in the editor UI.

If this is not already in the works I'd be interested in working on a PR. Let me know if you've already thought through the design for this or related features.

**Comment by basarat** [comment]
I don't plan to offer much customisation. I'd like to offer a cohesive consistent but definitely opinionated experience. Sorry about that :-/ but hope you find it useful still :rose:
