### ISSUE TITLE
Hangs when loading alm in chrome

### ISSUE THREAD

**Issue by mbilling** [alm-tools/alm#183]
I'm running nodejs v5.12.0
I'm running chrome 52.0.2743.116 m (latest)

I have attached screenshot of how it looks. Nothing happens. Sometimes the basis UI appears, other times the browser stays white background, and loading forever
![alm-hanging](https://cloud.githubusercontent.com/assets/973790/18120008/be7e0b12-6f5d-11e6-8cae-49423a100901.PNG)

Tell what info you need!

**Comment by basarat** [comment]
What is the size of that directory? Thanks in advance 🌹

**Comment by mbilling** [comment]
@basarat 29401 files ind 3081 folders

**Comment by basarat** [comment]
> @basarat 29401 files ind 3081 folders

That is not a big file count. Should work fine. Suspect if you leave it open (try 5 mintues) it will catch up just fine. Definitely not the *desired* workflow but will help me debug if something has just gone :arrow_down: or only slow

**Comment by basarat** [comment]
I haven't been able to reproduce it so closing. 

PS: For wayyy to many files like `100,000`+ we gracefully give an error before exiting : https://github.com/alm-tools/alm/issues/233#issuecomment-252470466 Not the case for you I know but just that its something that should work.
