### ISSUE TITLE
Using alm remotely?

### ISSUE THREAD

**Issue by niieani** [alm-tools/alm#184]
Since ALM's interface is 100% browser-based, it should be possible to run the instance on a remote server and load it up securely locally. This would enable an awesome use case, where you could edit non-local code directly on a server.
Any thoughts on how we could achieve this?

**Comment by basarat** [comment]
> Since ALM's interface is 100% browser-based, it should be possible to run the instance on a remote server and load it up securely locally. This would enable an awesome use case, where you could edit non-local code directly on a server.

100% supported and was designed for this use case. People use it on a rasberry pi (server) https://twitter.com/xperiments/status/738691522854563840 as well as on chromebooks (client) https://github.com/alm-tools/alm/issues/133#issuecomment-234447482 and front-end colleagues at work used it to run a .net IIS + this on windows in a VM : and http the website on their mac + use this to edit the TypeScript.

Iris the defacto go web framework also allows you to edit server files through alm : https://kataras.gitbooks.io/iris/content/plugin-editor.html :rose: 


> load it up securely

You can enable HTTPs and Auth : https://basarat.gitbooks.io/alm/content/config/command-line.html :rose:

**Comment by niieani** [comment]
Awesome to hear that! Thanks.
