### ISSUE TITLE
How to see a list of methods/fields in a class?

### ISSUE THREAD

**Issue by 40rn05lyv** [alm-tools/alm#191]
How to see a list of methods/fields in a class and quickly jump to selected method/field?

**Comment by basarat** [comment]
> How to see a list of methods/fields in a class and quickly jump to selected method/field?

Key options: The semantic view : https://basarat.gitbooks.io/alm/content/features/semantic-view.html

Alternatively the symbol search : https://basarat.gitbooks.io/alm/content/features/omni-search.html#symbol-search :rose:
