### ISSUE TITLE
[TSCONFIG]: No active project

### ISSUE THREAD

**Issue by fiftin** [alm-tools/alm#196]
I run app in empty folder. And I receive next message:
```
Version: 2.0.0
DASHBOARD: http://localhost:4444
[TSCONFIG]: No active project
```

That is all. App does not start.

Environment: Windows 10, node v6.2.0, tsc 1.0.3, Chrome 53.0.2785.116 m (64-bit).

**Comment by basarat** [comment]
> I run app in empty folder. And I receive next message:

That is by design and is designed to help you :heart:. Please create a `tsconfig.json` and select it from the project selector : https://basarat.gitbooks.io/alm/content/features/omni-search.html#project-search

Open to suggestions for a better experience :rose:
