### ISSUE TITLE
shortcuts dont take into account other localizations

### ISSUE THREAD

**Issue by martov1** [alm-tools/alm#197]
Hi,

shortcuts like ctrl + ; and ctrl + / will not work on keyboards with other localizations (they are mapped to some other key) and there seems to be no way to change them.

Really nice work BTW.

**Comment by basarat** [comment]
Previous issue : https://github.com/alm-tools/alm/issues/154 (german keyboard). I understand the pain. But don't plan to work on it quite yet. The command palette is your only choice at the moment (https://basarat.gitbooks.io/alm/content/features/omni-search.html#command-search). I will setup a uservoice (or some service like that) at some point. Only leaving known bugs that should be immediately fixable or stuff that I am actively considering open at the moment. Thanks for your patience :rose:

**Comment by martov1** [comment]
got it, thanks anyways. im seriusly considering using this as my main
editor.
