### ISSUE TITLE
Code Blast Feature Request

### ISSUE THREAD

**Issue by anfrodriguezri** [alm-tools/alm#198]
Hi guys I was really attracted by the code blast feature which is pretty awesome but when I tried it (even though I was really exited) it got really anoying at the moment because of the shaking ( I can't program like that ). So just as a suggestion I think the shaking should go away and the users would enjoy more only having all the sparking effects. Great IDE, thanks for the developing.

**Comment by martov1** [comment]
+1

**Comment by basarat** [comment]
Indeed an excellent suggestion. I didn't plan it as something that is *actually usable*. But you've suggested to make it so. Will do :rose:

**Comment by basarat** [comment]
It still feels a bit gimicky and not something usable to me. And so I might bring back the shake at a future point. For now its gone with `2.0.2` :rose:
