### ISSUE TITLE
Feature request: auto indent

### ISSUE THREAD

**Issue by martov1** [alm-tools/alm#199]
Hi, any chance to implement an auto indentation feature in the future?
Maybe this could be implemented? https://github.com/vvakame/typescript-formatter

**Comment by basarat** [comment]
> Feature request: auto indent

Already does. Actually even *auto formats*. We do it on `enter` and `}` insertion :rose:

**Comment by martov1** [comment]
oh nice, I didnt found it in the docs and on the omni tool, sorry.

**Comment by basarat** [comment]
> oh nice, I didnt found it in the docs and on the omni tool, sorry.

My bad. Thanks for pointing out missing docs. Added : https://basarat.gitbooks.io/alm/content/features/formatting.html :rose:

**Comment by basarat** [comment]
![autoformat](https://cloud.githubusercontent.com/assets/874898/18613828/a8f1b5ac-7dc5-11e6-9807-7d62e602abbd.gif)
