### ISSUE TITLE
React UI Designer

### ISSUE THREAD

**Issue by basarat** [alm-tools/alm#207]
This is purely an idea I am thinking about that I might never do. But its become complex enough in my head for me to write down some *public* notes and get some feedback ❤️ : 

# Structor 

The defacto implementation of this is currently structor : https://github.com/ipselon/structor and its a great idea and a project you should check out :rose:

Having used drag and drop UI creators in the past, I quite prefer editing *live code* instead of property dialogs (especially with TypeScript). You can see e.g. the style property editor (on the right) in structor in the following screenshot: 

![](https://github.com/ipselon/structor/raw/master/images/title-background.png) 

I would rather edit the *code* (in TypeScript) at the bottom than that property dialog (Of course with live reload of the UI). Hence a different way to approach it below:

# What I am thinking of offering

I imagine something like: 

```ts
// Some file myButtons.tsx 

export const MyButton = (props) => <button {...props}/>

import almDemo = require('alm-demo');

almDemo('MyButton', ()=> { // alm-demo is actually a noop on true bundling.
   // Write whatever code e.g. 
   let content = "asdf"
   // Finally return a promise to something that is renderable
   return Promise.resolve(<MyButton>{content}</MyButton>);
}); 

// As any times as you want
almDemo('MyButtonState2', ()=> {
   let content = "bar"
   return Promise.resolve(<MyButton>{content}</MyButton>);
}); 
```

Then you set some entry point `main.tsx` using some config entry (e.g. `alm.json`) and we collect all these states `MyButton` / `MyButtonState2` etc into a navigable gallery where you select one of these and we show it to you with live reloading. Of course on this page you can use *true* react dev tools to debug this component if you wanted to.

# Question 

* Would you want something like this? Please leave a comment / like / share to give me sufficient motivation and ideas. Maybe its not a problem people want solved :rose:

**Comment by danielearwicker** [comment]
I say go for it!

**Comment by basarat** [comment]
I need this. So I will do this :heart:  Thinking through this here are the results: 

* Implementation wise any `building your js => bundle + live reloading` really requires webpack-dev-server which in turn will only work if we have the project `webpack.config.js` which in turn will only work if we have the project `package.json` + loaders configured inside that. So really this whole thing can (and should) be done as an npm package that the user gets into their project instead of an IDE integration.

So will work on it outside of alm for now :rose:

**Comment by basarat** [comment]
Based on the knowledge gained from making [eze](https://github.com/basarat/eze), it wasn't too hard, so done! :rose:

:memo: https://basarat.gitbooks.io/alm/content/features/live-demo-react.html

![demoreact](https://cloud.githubusercontent.com/assets/874898/22196418/387b4a32-e1a1-11e6-852b-ee65fa755db0.gif)
