### ISSUE TITLE
Install error 

### ISSUE THREAD

**Issue by nicolasxu** [alm-tools/alm#212]
sudo npm install alm -g

then got the following error
npm ERR! uid must be an unsigned int

**Comment by basarat** [comment]
Closing as an npm error : https://github.com/npm/npm/issues/6980 Suspect `npm install -g <somethingelse>`, e.g. `npm install -g webpack` will not work either.

If `webpack` (or any other global) doesn't work for you either few things to try: 

* Try reinstalling node / npm.
* Raise at https://github.com/npm/npm/issues 

Closing as external. Sorry for any inconvenience and feel free to discuss here further :rose:

**Comment by anupoju84** [comment]
I am seeing the same errors on Mac:

uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "gulp"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8

**Comment by basarat** [comment]
@anupoju84 verified Node / NPM bug : https://github.com/npm/npm/issues/13918 

Please downgrade NPM to fix : https://github.com/npm/npm/issues/13918#issuecomment-248993663 :rose:
