### ISSUE TITLE
non documented `outDir` required while using JavaScript support

### ISSUE THREAD

**Issue by martov1** [alm-tools/alm#216]
Hi,  thanks for all your work, i love using alm.

I'm trying to use javascript support as explained here on the docs:
https://basarat.gitbooks.io/alm/content/features/javascript.html
and i get the following error.
`You must use an `outDir` if you are using `allowJs` in tsconfig.json`

Edit: adding an outDirr parameter set to a non-existing directory will output the transpiled js/ts on that directory upon save.

**Comment by martov1** [comment]
thanks <3

**Comment by basarat** [comment]
> adding an outDirr parameter set to a non-existing directory will output the transpiled js/ts on that directory upon save

Yup. If you don't want that set `compileOnSave` to false https://basarat.gitbooks.io/alm/content/config/tsconfig.html :rose:

**Comment by martov1** [comment]
yup, thanks for pointing it out. i'm just starting out with ts so i didnt know that those were actual typescript compiler parameters, i will go and read it's docs.
