### ISSUE TITLE
Intergrating simple server for live development 

### ISSUE THREAD

**Issue by sathyesh** [alm-tools/alm#218]
Is there a way to integrate simple server for live development ,so that changed files ,will automatically reload in browser.

Thanks,
Sathyesh

**Comment by basarat** [comment]
> Is there a way to integrate simple server for live development ,so that changed files ,will automatically reload in browser

I thought about that for myself as well, but realized that we most likely want to use bundling (commonjs) etc with that and you probably need control on that configuration. That is something that `webpack.config.js` is for. So recommend going all in and just using webpack-dev-server. Here is a quick start : https://basarat.gitbooks.io/typescript/content/docs/quick/browser.html#live-reload :rose:
