### ISSUE TITLE
Feature request: prioritize object methods and properties over snippets and global vars after a dot

### ISSUE THREAD

**Issue by martov1** [alm-tools/alm#219]
Suggestion: 
after a dot alm tends to suggest every autocomplete option in alphabetical order.

Maybe it makes more sense to show methods and properties at the top and snippets and documentation annotations at the bottom when detecting something that looks like 

`myvar.`

I think having methods at the top is specially helpfull, since (in my case at least ) when working with third party libraries it exposes me to the available functions and i can read the names and refresh a bit the functionality provided by the library.

![004b89f2-3ad4-11e6-84dd-82ec1fe53e2b](https://cloud.githubusercontent.com/assets/7854453/19028123/f8c99a5a-890e-11e6-9214-3616090364e6.jpg)

In the same way, when in a comment block, it would be usefull to list all the documentation annotations first.

As always, thanks for your outstanding work.

**Comment by basarat** [comment]
Completely agree. I had it working at some version of monaco. We have our own custom build : https://github.com/basarat/monaco/blob/2fa914a0bea83ac4aa3fc932f733b3af44c05432/extensions/preBuild.ts#L386-L392 that fixes the order just like you suggested. However its broken over some upgrades of monaco. Will add it back when I have some time :rose:

**Comment by basarat** [comment]
Note to self: With monaco latest (only on master) `import` no longer matches the snippet as shown below: 

![image](https://cloud.githubusercontent.com/assets/874898/19289968/f88bb64e-9058-11e6-92ef-222d8b3013a1.png)


Fix it as I do import a lot

**Comment by basarat** [comment]
Released with `2.5.0` :rose:
