### ISSUE TITLE
Dependency analysis

### ISSUE THREAD

**Issue by basarat** [alm-tools/alm#22]
perhaps use this api endpoint : https://github.com/Microsoft/TypeScript/pull/3687 if it lands

**Comment by basarat** [comment]
Done

**Comment by ksikka** [comment]
I came here from that PR. How did you resolve your issue? The PR hasn't been merged (at time of writing).

**Comment by basarat** [comment]
@ksikka Indeed that PR hasn't been merged. But the feature has been implemented https://github.com/alm-tools/alm/blob/master/docs/features/README.md#dependency-view :rose:
