### ISSUE TITLE
Debug functionality

### ISSUE THREAD

**Issue by denkomanceski** [alm-tools/alm#235]
This is a question and not an issue of course. Is it possible to debug an app through this ? I searched through the documentation but cant seem to find Debugging section. I am using angular2 

Regards and thanks for this awesome tool

**Comment by basarat** [comment]
> Is it possible to debug an app through this ?

Nope. I've come to this multiple times in my head but for me `console.log` works best (tip snippet `log`). 

I've seen the vscode debug support and its the best in class. That said I can also the hacks they need to do for it to work and its not something I can maintain externally easily. At least not yet :rose:

**Comment by basarat** [comment]
Thinking about this more, the chrome dev tools are really awesome and I'd like to continue to use them instead of learning any UI I would build in-house. So closing :rose:
