### ISSUE TITLE
Command : Git add all and push current branch

### ISSUE THREAD

**Issue by tomitrescak** [alm-tools/alm#237]
@basarat i can't say enough thanks for this amazing ide. I am testing it with my students and it seems like a perfect classroom material for student projects. I have currently set up two projects that run in cloud and students learn basics of unit testing. I have one isssue though. You do support some gift functionality, yet there is no support for commits and pushes. Would you consider that functionality? Or even better would be to have a full terminal access via predefined user. Thanks again!

**Comment by basarat** [comment]
> Or even better would be to have a full terminal access

There isn't a solution available that doesn't leverage `node-gyp` at the moment : https://github.com/alm-tools/alm/issues/133#issuecomment-248539599. That can be a painful install experience for users and really want just `node` + `npm install` (no python , c++ toolchain).  Will not be adding it till a pure js solution appears, or I have time to create a `pty` clone in js, or node-gyp becomes better.

>  You do support some gift functionality, yet there is no support for commits and pushes

It will never be as good as Sourcetree, but I can add that. A single command `Git add all, commit and push` > shows you a screen to edit the commit message sound fair? :rose:

PS: thanks for giving it a go :heart:

**Comment by tomitrescak** [comment]
@basarat yes, git add all, commit and push would be fantastic! Then I can truly run it in the cloud. 

You are only 2 stars till 1000! :)

**Comment by basarat** [comment]
Released with `2.5.1` :rose: 

Docs : https://basarat.gitbooks.io/alm/content/features/git.html 

![](https://raw.githubusercontent.com/alm-tools/alm-tools.github.io/master/screens/git/gitAddAllCommitAndPush.gif)

I'm glad you asked for it. I'll be using it quite a bit for my own work :heart:

**Comment by tomitrescak** [comment]
Wow, that was fast! Thanks!
