### ISSUE TITLE
Alm slow, "error analysis duration: 21s, lint cancelled"

### ISSUE THREAD

**Issue by martov1** [alm-tools/alm#239]
Hi, I'm starting out a project and alm is getting very slow and linting seems to be failing.
![sin titulo](https://cloud.githubusercontent.com/assets/7854453/19253753/e6cc20f0-8f23-11e6-9106-f5be280bbee0.png)

I'm working on an SSD so I/O should not be an issue.

I tried only including the surce directory and excluding the build dir, temp dirs and node_modules dirs, but it does not seem to have any effect.

This is the project i'm using (mostly a yeoman generator out of the box) in case you want to reprodue the issue.

it's a bit big so i compressed it and uploaded it on a free file hosting service because github seems to have a max filesize of 10mb.
http://www.filedropper.com/dominiqueuiclient

**Comment by basarat** [comment]
I am unable to see the error analysis duration up like the sample you showed : 

![image](https://cloud.githubusercontent.com/assets/874898/19254871/0f206ca2-8fa4-11e6-8344-d862147a95e5.png)


However the linter is indeed getting cancelled. I'll look into it :rose:

**Comment by basarat** [comment]
The linter was actually crashing. This is because a rule `no-duplicate-key` was not found. We now print a stacktrace :rose:

![image](https://cloud.githubusercontent.com/assets/874898/19254987/4cd65d26-8fa5-11e6-91da-ee3e5199e75d.png)

Released with `2.3.1`. That said, if there is still a bug let me know. 

PS the following tsconfig is fine (no need for `filesGlob` or any special exclude based on your project structure): 

```
{
  "compilerOptions": {
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "compileOnSave": false,
  "include": [
    "src/**/*.ts"
  ]
}
```

**Comment by basarat** [comment]
The tslint error is my fault. I upgraded to 4.x without looking at what was changing. Certain rules are removed : https://github.com/palantir/tslint/issues/1507. I'll cut a release with the downgrade to 3.x soon :rose:

**Comment by basarat** [comment]
`2.5.0` should be less buggy and faster :rose:
