### ISSUE TITLE
file watcher continuously eats CPU

### ISSUE THREAD

**Issue by wizzard0** [alm-tools/alm#258]
windows 10, Node v6.6.0

**Comment by wizzard0** [comment]
also runs out of memory eventually:
```
Security context: 2EE7B815 <JS Object>
    1: _send [internal/child_process.js:627] [pc=38793FA3] (this=2EE860DD <a process with map 0C50E9AD>,message=0492EEDD <an Object with map 12E32085>,handle=2EE081D9 <undefined>,options=0492EB5D <an Object with map 12E31AD9>,callback=2EE081D9 <undefined>)
    2: send [internal/child_process.js:538] [pc=387692A0] (this=2EE860DD <a process with map 0C50E9AD>,message=0492EEDD <an Object with map 12E320...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
fileListingWorker worker restarting. Don't know why it stopped with code: 3
```

**Comment by basarat** [comment]
Which version of alm? This happened to me on a folder too big. Should have errored instead of crashing badly. 

refs https://github.com/alm-tools/alm/issues/233 which was fixed in `2.3.0` :rose:

**Comment by wizzard0** [comment]
alm 2.5.2

**Comment by basarat** [comment]
How many files in working dir?

**Comment by wizzard0** [comment]
Maybe 500

**Comment by basarat** [comment]
Total files please. The file watcher looks at *all* files and essentially powers file open + tree view. 

More than 100000 or less https://github.com/alm-tools/alm/commit/e292122b61fd3a8365e6ac743e53bfc39aedd9ad#diff-d67e176d5b2909056b10c3b5ed4a1c8eR15

**Comment by wizzard0** [comment]
2500 files

**Comment by basarat** [comment]
> 2500 files

That is not a lot at all. Thanks for helping me with the stats. 

Sadly, short of reimplementing chokidar I can't think of a better solution. Closing as external for now (similar to https://github.com/alm-tools/alm/issues/202)
