### ISSUE TITLE
multiple project support

### ISSUE THREAD

**Issue by wizzard0** [alm-tools/alm#259]
when there are multiple node modules written in typescript linked via npm link

**Comment by basarat** [comment]
Only one tsconfig is supported at a time : https://basarat.gitbooks.io/alm/content/features/omni-search.html#project-search as it greatly reduces the edge case scenarios :rose:

**Comment by wizzard0** [comment]
That is a showstopper for using ALM for us, sadly :(

**Comment by basarat** [comment]
> Then that is a showstopper for using ALM for us, sadly

That's fine. Basically things like doc viewer , autocomplete, error handling all become complicated. Simply think of errors : a statement like `foo = 123` might be error in one project (`foo not available`) but not in another or it might be different error (`not available` vs. `number not assignable to string`). You generally want to work on a single project at a time but YMMV 👍

**Comment by wizzard0** [comment]
well, what's the problem with running multiple independent language servers for different independent projects?..

**Comment by basarat** [comment]
The UI is singular and needs to decide what to show
