### ISSUE TITLE
Build error on Windows

### ISSUE THREAD

**Issue by BurtHarris** [alm-tools/alm#275]
Cloned the repository and invoked `npm i` on my Windows 10 laptop.   I got what looks like bash related errors.   Unfortunately, I don't know bash well.   What am I missing?

```
> alm@2.5.3 prepublish C:\code\alm
> bash ./scripts/prepublish.sh

: invalid optionlish.sh: line 2: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
./scripts/prepublish.sh: line 3: $'\r': command not found
./scripts/prepublish.sh: line 5: npm: command not found
./scripts/prepublish.sh: line 6: $'\r': command not found
./node_modules/.bin/webpack: 12: ./node_modules/.bin/webpack: node: not found
```

**Comment by basarat** [comment]
> What am I missing?

git comes with a bash shell. You should be able to type `bash` from ` cmd` and then run `npm install` : https://github.com/alm-tools/alm/blob/master/docs/contributing/README.md#requirements :rose:

**Comment by BurtHarris** [comment]
OK, cool.   That works.   I guess this represents some sort of incompatibility in the Windows10 bash, is that right?

**Comment by basarat** [comment]
> I guess this represents some sort of incompatibility in the Windows10 bash, is that right?

Hmm probably. I don't have windows 10. Win 8 on my home machine. PS: win 10 bash is still in *beta* so not worth much trying to figure out how to get it working :rose:
