### ISSUE TITLE
How can I create public alm server?

### ISSUE THREAD

**Issue by Sihyung-Park** [alm-tools/alm#302]
Hi,

I'm using alm tools to work with my team.
I'm trying to host an alm server so that my team can reach project folder even with external IP addresses.

I tried `alm --host 0.0.0.0` but it only allowed access from local address.
I tried `alm --host 55.55.55.55` too (assume that `55.55.55.55` is my IP address, but it returned an error:
At first I thought it was a port problem, but it didn't work even though I changed the port number to unused one.

Below is the error message thrown.

```
Version: 2.6.0
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 55.55.55.55:4444
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:609:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

I tried to figure out the problem, but could not find the right solution.

I'd really appreciate your reply.
Thanks for your works!

**Comment by basarat** [comment]
`alm --host 0.0.0.0` should definitely work. Perhaps a firewall?

> Thanks for your works!

Thanks :) :rose:

**Comment by Sihyung-Park** [comment]
Launched alm server with `alm --host 0.0.0.0`, and it returned no error.

```
Version: 2.6.0
DASHBOARD: (launched in browser) http://localhost:4444
TSCONFIG: All Good! /Users/my/project/path/tsconfig.json
[TSC] Started Initial Error Analysis: /Users/my/project/path/tsconfig.json
[LINT] No tslint configuration found.
[TSC] Error Analysis Duration: 3s
[TSC] FileCount: 0  Errors: 0
[TSC] Incremental Error Analysis /Users/my/project/path/tsconfig.json
[TSC] Error Analysis Duration: 1s
[TSC] FileCount: 0  Errors: 0
```

I can open it with browser at my local ip address, but I still can't access it with external IP 😢 (FireWall was turned off, however it returns connection time out error)

I'm using alm on macOS 10.12. What might possibly be the problem?

Thanks, again!

**Comment by basarat** [comment]
Try running a simple http server : https://www.npmjs.com/package/http-server Does *that* work?

**Comment by Sihyung-Park** [comment]
`http-server` worked just fine, even from external IP address.

It was strange that the same nodejs server didn't worked with alm, so I assumed that there might have a problem occurred at the process of installing alm (or after install..). So I deleted the whole ALM package and clean-installed it, and now it works!

Still don't understand why it didn't allow access from outside, but the problem is fixed.. little exhausted though.

Thank you very, very much for your help!

**Comment by basarat** [comment]
No worries. Have fun :rose:
