### ISSUE TITLE
Is there a version of ALM that aligns with the latest stable release of Typescript?

### ISSUE THREAD

**Issue by oimedia** [alm-tools/alm#387]
For some of us, we may be 'pinned' to using a stable release of Typescript.
For example in my current project I am using 2.1.4 and cannot update for reasons I will not go into here. 

ALM currently uses a later developer release, is there a tagged build that uses typescript 2.1.4?

Would it be useful to others to have a stable version of ALM tagged to each stable release of Typescript?

**Comment by basarat** [comment]
Its difficult to maintain a stable + well curated release of alm that works with a *range* of TypeScript versions. e.g. API changes like this https://github.com/TypeStrong/typedoc/issues/357 are necessary for the progress of TypeScript, but don't want to maintain two code paths, one of which will eventually become stale and we would be scared to change it. 

Of course this is doable with more resources but would like to keep following the simple coheisve experience with the target "Best for TypeScript latest" :rose:

**Comment by basarat** [comment]
Just one more thing, you normally get more errors with TypeScript latest than with TypeScript old. So *you* will not create new errors for old TypeScript by fixing the ones that you see in new TypeScript. You will normally find bugs in existing code that will make you look like a super star. This strategy has worked well for me in the past :heart:
