### ISSUE TITLE
Feature Request: Type Doctor

### ISSUE THREAD

**Issue by mavericken** [alm-tools/alm#391]
I think it would be nice if we had some sort of Type Doctor feature.

Example use case:

```
interface Test{
  prop1: string,
  prop2: number
}

var test:Test = {prop1:"hi",prop2:42,prop3:{a:1,b:"b"}};
```

Now Typescript is hurt because it didn't know about prop3.  So we execute the Type Doctor command.  Type Doctor does magic, and now code looks like this:

```
interface Test{
  prop1: string,
  prop2: number,
  prop3?: {a:number, b:string}
}

var test:Test = {prop1:"hi",prop2:42,prop3:{a:1,b:"b"}};
```

Now Typescript is all better.

**Comment by basarat** [comment]
> Type Doctor

This already exists and is called `QuickFix`. Docs : https://basarat.gitbooks.io/alm/content/features/quickfix.html

Ad a quick fix for adding members to an existing on assignment `=` already exists : https://github.com/alm-tools/alm/blob/master/src/server/workers/lang/quickFix/quickFixes/addClassMember.ts that *can* be used as a template to add members on `:` as well.

But recently TypeScript got support for a `CodeActions` that are also supported by us, given that there is a way no in TypeScript proper would rather that it be added there : https://github.com/Microsoft/TypeScript/issues and we get this automagically (as we pickup any TypeScript code actions as quickfixes as well) :rose:

**Comment by mavericken** [comment]
Oh cool thanks!
