### ISSUE TITLE
100k files limit

### ISSUE THREAD

**Issue by Mosho1** [alm-tools/alm#392]
Hi, I tried to open the project I'm working on using this, but it exits because of the files limit. Most of the files are from node_modules naturally, is there a way to ask alm to ignore them?

**Comment by basarat** [comment]
> , is there a way to ask alm to ignore them

You can edit the `.js` file right next to it after `npm install alm -g` https://github.com/alm-tools/alm/blob/e292122b61fd3a8365e6ac743e53bfc39aedd9ad/src/server/workers/fileListing/fileListingWorker.ts#L15 

We need to write a better file listing worker that still doesn't add complexity to this project. Really wish that this was something that operating systems / node community would have solved and sad that it isn't. I suspect you most likely are running it in the wrong folder though, but I might be wrong :rose:
