### ISSUE TITLE
Should not crash when it cannot access a sub-directory

### ISSUE THREAD

**Issue by doliver3** [alm-tools/alm#417]
ALM tools refuses to run when it does not have access to a sub-directory.  This is very poor behavior since it means that it can never be used if any sub-directories do not have full permissions. 

Instead, the behavior should be to ignore the folder that does not have permissions and still support the rest of them. 

DASHBOARD: (Please open in chrome) http://localhost:4444
Exiting: Permission error when trying to list /Users/beyondenergy/Applications.
- Start the IDE in a project folder (e.g. '/your/project')
- Check access to the path

**Comment by basarat** [comment]
I agree this is not ideal. However to have full deterministic behaviour (which is lacking in other IDEs) about "if there is an error ... there is definitely an error and not a file syncing issue" we need to watch all the files. If it didn't error in this case it would have errored with out of memory eventually anyways (can't watch too many files). 

Again I agree that it is inconvinient, but needed to offer a first class "never wrong" experience :rose:
