### ISSUE TITLE
How can I set the editor font-size

### ISSUE THREAD

**Issue by danielo515** [alm-tools/alm#420]
Hello,

Thanks for this awesome editor.
I would love to adjust the editor's font size.
I was unable to find any configuration to do it.

Regards

**Comment by basarat** [comment]
There is no configuration for it. You need to zoom the browser window e.g. how I have it here : https://egghead.io/lessons/typescript-simplify-asynchronous-callback-functions-using-async-await (zoomed to 125%) :rose:

**Comment by danielo515** [comment]
I want to make the letter smaller, not bigger. Considering that the font of the sidebar is already very small I don't think this is a workable solution.

**Comment by basarat** [comment]
> Considering that the font of the sidebar is already very small I don't think this is a workable solution.

I understand. However adding them-ability / customisability is not on my current goals. An amazing (opionionated) default UX is what I am going for :rose:

**Comment by danielo515** [comment]
Dear @basarat 

I understand your position, fair enough. If you don't want to provide such option, what about relying on the default browser's functionalities? As you said, the zoom can be used. If you make the file navigation sidebar the same font-size as the editor, then the browser zooming will be consistent and usable.
