### ISSUE TITLE
Getting JSX to work inside Monaco

### ISSUE THREAD

**Issue by mrjjwright** [alm-tools/alm#421]
Hi,

I was wondering the steps necessary to get JSX to compile inside a Monaco editor.  I added the React.d.ts file using `monaco.languages.typescript.typescriptDefaults.addExtraLib` but I still get an compiler error when doing something as simple as this `Cannot find name div`:

<img width="666" alt="screen shot 2017-02-06 at 5 22 24 pm" src="https://cloud.githubusercontent.com/assets/4343/22672391/db983cf8-ec90-11e6-9389-b86db738aa3c.png">

I noticed you don't use `monaco.languages.typescript.typescriptDefaults.addExtraLib`.   How do you get the user's ever changing TS files into alm in general?

**Comment by basarat** [comment]
> How do you get the user's ever changing TS files into alm in general?

My own TypeScript mode backed by own language service host: https://github.com/alm-tools/alm/blob/f013768ece2d132bb41806f970c1d4cc7eb3b80f/src/app/monaco/languages/typescript/monacoTypeScript.ts :rose:

**Comment by basarat** [comment]
I also had to write quite a bit of logic to get the best in class syntax highlighting for JSX https://basarat.gitbooks.io/alm/content/contributing/syntax.html :rose:

**Comment by mrjjwright** [comment]
But at a high level is it even possible to get Monaco to parse TSX files to React.createElement calls. I thought the tsc compiler could do that but perhaps I am wrong.

**Comment by basarat** [comment]
> . I thought the tsc compiler could do that but perhaps I am wrong.

TSC can indeed parse them. You need to set `jsx: react` flag in the config and make sure the file extension `.tsx` is captured when adding the file to the compilation context. 

Note I am unaware / unskilled in doing *language analysis inside monaco*. I just uses TypeScript / TypeScript compiler API directly :rose:

**Comment by mrjjwright** [comment]
Gotcha, makes sense, thanks!
