### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by RavirajParab** [alm-tools/alm#440]
When I setup ALM for typescript , I see that my active project does not get set. When I add any new file, at the bottom of page it shows "File is not a part of currently active project, robots deactivated". Very vague issue I am facing. Please help

**Comment by basarat** [comment]
> "File is not a part of currently active project, robots deactivated".

Click on it and you get to chose any `tsconfig.json` files in current working dir: 

![demo](https://cloud.githubusercontent.com/assets/874898/23287124/99e8ddaa-fa8f-11e6-85d5-bb840a21b23b.gif)

Also worth going through the quickstart : https://basarat.gitbooks.io/alm/content/quickstart.html :rose:

**Comment by RavirajParab** [comment]
Hi Basarat,

I followed your quickstart page . I am stuck at the add new file step. I see that when you add new file test.ts , it is immediately forms part of that project. That is indicated by lower icon of robots turning green. That does not happen in my case. I can get my file added but the lower robots deactivated still remains. I am unable to find why is this happening .

What I did is , I use Windows. I created a folder c:/TS . In npm, I did CD to come to my directory,I fired npm install typescript -g , npm i alm -g , alm -i to create config file and finally I hit alm . Which gives me URL at port 4444 which I opened in chrome.

Now I see proper tsconfig file already selected. Now I add new file and see that robots are still deactivated, ideally it should have got activated and created an equivalent is file . That is not happening.

**Comment by basarat** [comment]
> Now I add new file and see that robots are still deactivated,

Can I have a screenshot? :rose:

**Comment by RavirajParab** [comment]
Hello Basarat, Yes sure. Please find the document below which have all necessary screenshots.
😿

[440.docx](https://github.com/alm-tools/alm/files/798575/440.docx)

**Comment by basarat** [comment]
Thanks for the excellent repro ❤️ ! . I need to update the startup guide. Basically I've changed the default `tsconfig.json` generated to include files from a `src` directory and compile to a `lib` directory. 

So you need to create the new file in a `src` folder. 

Reason: 
* This workflow works a lot better when publishing your TypeScript package to NPM :rose:

**Comment by RavirajParab** [comment]
Let me try out that and let you know. Thanks for extensive help.

**Comment by basarat** [comment]
@RavirajParab Thanks for testing ! :rose:

Leaving open as I need to update the quickstart :rose:

**Comment by RavirajParab** [comment]
Yup, sure :rose:

**Comment by basarat** [comment]
Updated the quickstart :rose: :heart:
