### ISSUE TITLE
launch fails, complaining about string value of `declarationDir`

### ISSUE THREAD

**Issue by eliranmal** [alm-tools/alm#460]
### description

when loading a project with alm, and the *tsconfig.json* file has an entry for `declarationDir`, alm complains about the value type.

### steps to reproduce

- create a new typescript project
- add a *tsconfig.json* file, with `declaration` set to `true`, and `declarationDir` set to some string, e.g. `"typings"`
- navigate to the project directory, and run alm

### expected result

alm should be launched with no error regarding the value of `declarationDir`, as a string value is [legal in the latest version of typescript][1].

### actual result

alm starts with the following error:

    TSCONFIG: Error Key: 'declarationDir' has a value '"typings"' of an invalid type: string

### environment details

- operating system: OS X 10.11.6 (15G1108)
- node version: 6.9.1
- npm version: 3.10.8
- tsc version: 2.2.1

[1]: https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by basarat** [comment]
Thanks! Fix released with `2.34.0` :rose:

**Comment by eliranmal** [comment]
that was quick! thank you :)
