### ISSUE TITLE
File tree view side panel is too small 

### ISSUE THREAD

**Issue by nidin** [alm-tools/alm#508]
**What?**
File tree view side panel is too small. It's better to have a scale up/down icon.

**Screenshot**
![image](https://cloud.githubusercontent.com/assets/198246/24955641/87b02bf6-1f84-11e7-8503-28d4bbf41b78.png)

**Comment by basarat** [comment]
Thanks :heart:. Intentional though. Reason: It gets busy really fast (too many folders). You can momentarily increase browser window zoom if you find it annoying :rose:

**Comment by nidin** [comment]
If I increase the browser window the whole GUI scales up and it will lead to continues scale up/down when switching file editor and file tree. File tree is very tiny in big monitors.

![image](https://cloud.githubusercontent.com/assets/198246/24958940/5e0f8da2-1f91-11e7-9254-707c12421c76.png)

**Comment by nidin** [comment]
scaled up version 

![image](https://cloud.githubusercontent.com/assets/198246/24959055/cc226b20-1f91-11e7-9838-1f170a384d7e.png)

**Comment by hoegge** [comment]
Agree with @nidin - the tree view window and the semantic view window fonts are too small and it would be nice to be able to scale them relatively to the editor font

**Comment by nidin** [comment]
ALM is a nice tool but its not configurable to meet users tastes.
