### ISSUE TITLE
Feature request: VIM Key Binding Support

### ISSUE THREAD

**Issue by olivoil** [alm-tools/alm#510]
It would greatly help adoption for vim users

**Comment by basarat** [comment]
Sadly not a vim user so will not happen. Thanks for requesting though (appreciate the concern :heart:). 
Closing since I will not get to it :rose:

**Comment by olivoil** [comment]
@basarat thanks for the reply! If one wanted to contribute vim support, would you be interested? Any tips on what it would take and where to start?

**Comment by basarat** [comment]
> If one wanted to contribute vim support, would you be interested

Thanks but sadly no. Reason: This project saves me a bunch of time with TypeScript training and work. Sadly adding features that I don't use goes in the reverse direction :rose:
