### ISSUE TITLE
Embedding alm into a web page

### ISSUE THREAD

**Issue by ceymard** [alm-tools/alm#539]
Is there a way to embed alm to a web page so that people may use it and make some kind of playground online ?

Currently it would seem that this editor only exists to work locally. I would like to use it to power a demo page online for people to fiddle with my library.

**Comment by basarat** [comment]
> I would like to use it to power a demo page online for people to fiddle with my library

Not supported. Needs a server with an actual file system.

FWIW I did make a TypeScript playground for TypeStyle : http://typestyle.io/play/ 

Code : https://github.com/typestyle/typestyle.github.io (best explored by cloning and opening the project in alm) :rose:
