### ISSUE TITLE
Intalling failed

### ISSUE THREAD

**Issue by James-Don** [alm-tools/alm#54]
Though no error message at installing, running alm at command console it says command not found. My npm version is 3.3.12 and node version is 5.3.0 on Windows 8.

**Comment by basarat** [comment]
@James-Don thanks for your interest :rose: 

Its not on NPM yet as I don't want to push something that half works. See : https://github.com/alm-tools/alm#usage

**Comment by basarat** [comment]
Closing as this is the newest issue and the title can be confusing for potential contributors 🌹
