### ISSUE TITLE
"strict" is not recognized as a valid compiler option in tsconfig.json

### ISSUE THREAD

**Issue by psumstr** [alm-tools/alm#543]
@basarat The new `strict` option in Typescript 2.3 for tsconfig.json is not recognized as valid by alm.

On a side note, if you run tsc --init, the created tsconfig.json will now have comments for all options. alm doesn't like the comments, but I guess that's because it's not valid JSON.

**Comment by basarat** [comment]
`2.36.1` :rose: :heart:
