### ISSUE TITLE
zsh: command not found: alm

### ISSUE THREAD

**Issue by davidmoshal** [alm-tools/alm#55]
`OSX 10.11.3`
Ran:

```
npm install alm -g

alm .
```

got:

```
zsh: command not found: alm
```

**Comment by basarat** [comment]
> npm install alm -g

You need `sudo npm install alm` on a Mac/Linux flavored OS.

That said there is nothing useful on NPM yet :rose: 

![image](https://cloud.githubusercontent.com/assets/874898/13763629/b5fab874-ea9b-11e5-8898-ad1c1cfea6e7.png)

From https://github.com/alm-tools/alm#alm-tools-for-typescript 

![image](https://cloud.githubusercontent.com/assets/874898/13763637/c3490576-ea9b-11e5-9438-5fdea6271c85.png)

From http://alm.tools/

**Comment by davidmoshal** [comment]
sudo didn't help either, tried both:
`sudo npm install alm`
and 
`sudo npm install -g alm`
still got:
`zsh: command not found: alm`

**Comment by davidmoshal** [comment]
ps: I'm a big fan of your book  [TypeScript Deep Dive](https://basarat.gitbooks.io/typescript/content/)

best book on TS to date, always have it open when I'm working on TS (including now)

Thanks

David

**Comment by basarat** [comment]
Thanks! Indeed the version on `npm` doesn't have `bin` setup in its package.json ([like we do in master](https://github.com/alm-tools/alm/blob/894a6f095ecc84c8e32adf79c1bb7d595eba877d/package.json#L6-L8))

Leaving it open for now. Will automatically be fixed once I start supporting automated NPM publishing (I already have the tech ... just don't want to do the support without sufficient interest) :rose:

**Comment by davidmoshal** [comment]
Thanks, question regarding your book: is it up to date on latest 1.8 features?   
Seems like 1.8 added a LOT of functionality to TS.

**Comment by basarat** [comment]
> Thanks, question regarding your book: is it up to date on latest 1.8 features?

Not all of them. I keep a running log of things I need to document here : https://github.com/basarat/typescript-book/issues you can see it has stuff like module augmentation https://github.com/basarat/typescript-book/issues/75 in there. I need to figure out the right place in the book for stuff like this, which is generally what delays the process :rose:

**Comment by davidmoshal** [comment]
Thanks, the whole module system with TS is confusing at best.
And, integration with JS seems more mythical than actual, at least I haven't found any documentation on it.

Great job on the book!
