### ISSUE TITLE
Adjust Font Size / Line Height / Zoom

### ISSUE THREAD

**Issue by alohaninja** [alm-tools/alm#557]
Is there a way with Monaco to adjust the font sizes? It seems that when zooming with the browser the cursor gets incorrectly positioned. Font sizes are not consistent in semantic, tree view, and editor. Would be great to have a font type / size selector. 

Thanks!

**Comment by basarat** [comment]
> . Would be great to have a font type / size selector.

Has been asked before. But will likely never get done.

>  It seems that when zooming with the browser the cursor gets incorrectly positioned.

I haven't experienced that. Would love a screenshot. Once verified will need to be reported here https://github.com/Microsoft/vscode/ :rose:
