### ISSUE TITLE
Missing peer dependencies - unable to resolve with NPM

### ISSUE THREAD

**Issue by hoegge** [alm-tools/alm#566]
Maybe this is an NPM question and not an ALM issue, but I cannot get the peer dependencies right with ALM. I get the result below and both missing peer deps are from ALM

```
λ npm -g list --depth=0
C:\Users\mhpedersen\AppData\Roaming\npm
+-- alm@2.37.1
+-- curl@0.1.4
+-- jslint@0.10.3
+-- lite-server@2.3.0
+-- npm@5.3.0
+-- npm-install-peers@1.1.0
+-- source-map-explorer@1.4.0
+-- tslint@5.5.0
+-- typedoc@0.7.1
`-- typescript@2.4.1
npm ERR! peer dep missing: typescript@>=2.0.0 || >=2.0.0-dev || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev, required by tslint@5.0.0-dev.0
npm ERR! peer dep missing: typescript@>=2.0.0 || >=2.0.0-dev || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >= 2.4.0-dev, required by tsutils@1.9.1
```
 and they are both under ALM. I have tried to install different version of Typescript incl 2.5 but I still get the complaint. I have searched Google and NPM documentation without luck. Any help appreciated since I'd like to use ALM more as editor. Thanks and sorry for "abusing" this forum - but unsure where to ask and whether there could be something wrong with the dependencies in the ALM package.
```
λ npm -g list --depth=2
C:\Users\mhpedersen\AppData\Roaming\npm
+-- alm@2.37.1
| +-- basic-auth-connect@1.0.0
| +-- byots@2.5.0-dev.20170626.4.12
| +-- chalk@1.1.3
| | +-- ansi-styles@2.2.1
...
| +-- tslint@5.0.0-dev.0
| | +-- babel-code-frame@6.22.0
| | +-- colors@1.1.2 deduped
| | +-- diff@3.2.0 deduped
| | +-- findup-sync@0.3.0
| | +-- glob@7.1.2 deduped
| | +-- optimist@0.6.1
| | +-- resolve@1.3.3 deduped
| | +-- tsutils@1.9.1
| | `-- UNMET PEER DEPENDENCY typescript@>=2.0.0 || >=2.0.0-dev || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >= 2.4.0-dev
| +-- UNMET PEER DEPENDENCY typescript@2.5.0-dev.20170627
```

**Comment by basarat** [comment]
> whether there could be something wrong with the dependencies in the ALM package.

This is my fault. But it should work fine. TSlint support is not ideal as we track TypeScript nightly + tslint nightly but the latest Tslint nightly only *optomistically* works with TypeScript nightly. 

Haven't had issues with it yet though so just consider it a warning as it works (unless you find it doesn't in which case create a bug 🐛 report here). 

All this said. I don't use tslint much as TypeScript is becoming pretty *linty* lately ;) :rose:
