### ISSUE TITLE
Lint runs on all files every time instead of refreshing current file only / first

### ISSUE THREAD

**Issue by hoegge** [alm-tools/alm#568]
I think I read somewhere, that ALM would Lint as you edit the typescript file, but when I open a big project (250+ files) it lints all files every time, so it takes about 20 seconds to get it updated, i.e., the errors and markings stays on several lines and at wrong positions after you have edited them for up to 20 seconds. Not sure if Lint has to look at all files to do a good job or if you could update only the open file first and then lint the others afterwards in the background?

PS: ALM looks really great and promising.

**Comment by basarat** [comment]
Linting is *whole* project basis. Reason here https://github.com/alm-tools/alm/blob/9de3a34a821b3814337ed2dddbbc8fd595f0fad9/src/server/workers/lint/lintWorker.ts#L267-L270 

We could *lint* just the change file and *then* lint the remaining files. That is what we do for *ts type checking*. Will consider in future :rose:
