### ISSUE TITLE
CTRL-P opens printer dialogue

### ISSUE THREAD

**Issue by elmerbulthuis** [alm-tools/alm#57]
When i start alm, i get a message saying: 'Find a file to work with Ctrl+P'. When i hit CTRL-P on my chromebook, it opens the printer dialogue!

**Comment by elmerbulthuis** [comment]
it does on the npm version! but when i chekout master from git it seems to work!

**Comment by basarat** [comment]
@elmerbulthuis if you have focus on the browser *address bar* then it will open the print dialog (I don't think there is a way to intercept that). But if you have focus *anywhere inside* the browser `window` you get the file search :rose: 

Maybe I should add a note here : https://basarat.gitbooks.io/alm/content/features/omni-search.html

**Comment by basarat** [comment]
@elmerbulthuis I think its because the version on npm is broken : https://github.com/alm-tools/alm/issues/59 I am investigating :rose:

**Comment by basarat** [comment]
@elmerbulthuis this is fixed in v `0.0.20` onwards
