### ISSUE TITLE
Rename F2 shifts selection to wrong characters

### ISSUE THREAD

**Issue by hoegge** [alm-tools/alm#571]
When you select an identifier e.g. `variableName` in the text:
```ts
let variableName: number = 12;
console.log(variableName)
```
then the editor shifts the selection one character right when hitting `F2` and `ariableName:` is selected and you will "rename" that instead and also shifted one char right other places, so if e.g. the new name is `newVarName` it becomes:

```ts
let vnewVarName number = 12;
console.log(vnewVarName
```
which destroys the code

kr
Morten

**Comment by basarat** [comment]
Can't reproduce. Suspect unicode issues. Can you provide a zip file against this issue : https://github.com/alm-tools/alm/issues/260 :rose:
