### ISSUE TITLE
authentication feature

### ISSUE THREAD

**Issue by yuanoook** [alm-tools/alm#572]
This project is awesome. It edits files everywhere with the browser.
I use it directly on my server as remote editor. 

I hope there be authentication process before anyone can edit files on my server. 
So the files will be safe.

**Comment by basarat** [comment]
> I hope there be authentication process before anyone can edit files on my server.

There is.  https://alm-tools.gitbooks.io/alm/content/config/command-line.html  Use `https` and `auth` :rose:
