### ISSUE TITLE
Took forever to find live demo

### ISSUE THREAD

**Issue by toeknee581** [alm-tools/alm#574]
I kept looking for commands like start or debug.  It would be nice if there was a button that started / stopped live demo.

**Comment by basarat** [comment]
Search for `demo` : https://alm-tools.gitbooks.io/alm/content/features/live-demo.html

Reason why its not `start demo` is `start` is fairly general. Want to rank `demo` to give this as the first result in command search :rose: 

Why not `debug`  : We might eventually (who knows?) get actual debugger support (unlikely but still) :rose:
