### ISSUE TITLE
Any way to get indent guides (like in VS or Atom)?

### ISSUE THREAD

**Issue by hoegge** [alm-tools/alm#577]
Would it be possible to show / get indentation guides like in other editors?

[https://atom.io/packages/indent-guide-improved](url)

**Comment by hoegge** [comment]
Is the monaco-editor used in ALM taken from the Visual Studio Code (the full source) or from the Monaco Editor site (https://microsoft.github.io/monaco-editor/index.html) and would it be hard to update?

**Comment by basarat** [comment]
> Have you done a lot of changes so it would be a big task (for someone / me) to update it to the newest

Closing as this project is going in `take as is` mode :rose:
