### ISSUE TITLE
Git indicators colors review

### ISSUE THREAD

**Issue by hoegge** [alm-tools/alm#578]
Instead of a red dot for deletions a blue line is now indicating deleted lines, which looks a bit "un-intuitive". Is that a bug? 
![screenshot038](https://user-images.githubusercontent.com/15846310/29353058-384688f6-8269-11e7-8c7b-03a019840a42.png)
Also you could consider to use the same colors and indicators as in VSCode, to make it easier for people to transition (green: addition, blue: changes, red arrowhead: deletions):
![screenshot039](https://user-images.githubusercontent.com/15846310/29353221-c77a1baa-8269-11e7-9e18-fb66603633d2.png)

**Comment by basarat** [comment]
The colors used are specified here : https://github.com/alm-tools/alm/blob/83596ca02c0d53759cafc4ac0e4aab997395940c/src/app/monaco/addons/gitStatus.ts#L13-L45 

Leaving open to review when I have some time :rose:

**Comment by basarat** [comment]
I don't see myself changing it. A choice was made, perhaps not the best, but I can't see myself changing it for any reason.
