### ISSUE TITLE
Feature suggestion: Add icon file for Windows 

### ISSUE THREAD

**Issue by hoegge** [alm-tools/alm#579]
Would be nice to include a Windows .ico file to the `alm\resources` folder so Windows users can use that for shortcuts to projects by referring to `c:\Users\username\AppData\Roaming\npm\node_modules\alm\resources\icon.ico`. If you like the idea here is attached the png converted to ico:

[icon.zip](https://github.com/alm-tools/alm/files/1227442/icon.zip)

e.g. to add the button to Total Commander to easy launch ALM from current directory:
![screenshot041](https://user-images.githubusercontent.com/15846310/29353668-4b357ace-826b-11e7-905e-7bfe59c4e9b2.png)

**Comment by basarat** [comment]
Its shipped in the public folder : https://github.com/alm-tools/alm/blob/master/src/public/favicon.ico :rose:
