### ISSUE TITLE
Publish 2.37.4 to npm

### ISSUE THREAD

**Issue by cakenggt** [alm-tools/alm#583]
I specifically need certain features in typescript 2.6, however the version of alm published to npm (2.37.3) only has typescript version 2.5

**Comment by basarat** [comment]
Released `2.38.0` :rose:

**Comment by cakenggt** [comment]
The npm website says that the latest version is still 2.37.3 https://www.npmjs.com/package/alm

**Comment by basarat** [comment]
travis failed me https://travis-ci.org/alm-tools/alm/builds/318909328#L2468 It is a tagged commit. 

I've now published manually :rose:
