### ISSUE TITLE
Command line arguments | -t and -d

### ISSUE THREAD

**Issue by kataras** [alm-tools/alm#60]
When I run this: 
```
node C:\Users\kataras\AppData\Roaming\npm\alm --host 127.0.0.1 -t 4242 --user username --pass password  -d ./
```
The alm-tools running at 127.0.0.1:4444 not at 127.0.0.1:4242 (4242 is not used by other app)

And here comes the weird 
```
node C:\Users\kataras\AppData\Roaming\npm\alm --host 127.0.0.1 -t 4242 --user username --pass password -d C:\Users\kataras\Desktop\editor_example\scripts
```
// change -d  to: C:\Users\kataras\Desktop\editor_example\scripts ( it's the same as ./)
( I tried with 

1. -d C:\\\Users\\\kataras\\\Desktop\\\editor_example\\\scripts\\\ 

2. -d "C:\\Users\\kataras\\Desktop\\editor_example\\scripts" 

3. -d C:/Users/kataras/Desktop/editor_example/scripts also

) 

now didn't run at all :/ 

Error trace:

```
C:\Users\kataras\AppData\Roaming\npm\alm:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

```

**Comment by basarat** [comment]
<img width="647" alt="screen shot 2016-04-20 at 8 21 20 am" src="https://cloud.githubusercontent.com/assets/874898/14657381/e9bb28b4-06d0-11e6-9007-d17e48929bbb.png">

I couldn't reproduce not running on the right port (i.e. `-t` seems to work). Can you try it **without** `-d`?

-----

However I am sure there is a bug in `-d` (primarily because of the way I start worker background processes). I'll look at getting a repro on that and get back with results :rose:

**Comment by basarat** [comment]
> However I am sure there is a bug in -d

Couldn't find it. We start the workers with *absolute* file paths e.g. [here](https://github.com/alm-tools/alm/blob/c0bb5a16074e958568d9ea4586b2e98d06e78932/src/server/workers/lang/projectServiceMaster.ts#L48) and then the simple worker library ensures the process is forked with the correct `cwd` (current working dir)  [here](https://github.com/alm-tools/alm/blob/c0bb5a16074e958568d9ea4586b2e98d06e78932/src/server/utils/simpleWorker.ts#L296) which is needed for the loaded module to make `require` statements correctly. 

# More info

If you can please send me a screenshot of what happened when you ran: 

```
node C:\Users\kataras\AppData\Roaming\npm\alm --host 127.0.0.1 -t 4242 --user username --pass password  -d ./
```

# More 

I'm currently on my commute macbook. I'll try on a windows machine some-point today and get back at you :rose:

**Comment by kataras** [comment]
```
node C:\Users\kataras\AppData\Roaming\npm\alm --host 127.0.0.1 -t 4242 --user username --pass password  -d ./ 
```
http://imgur.com/ZGHroNI

**Comment by basarat** [comment]
> node C:\Users\kataras\AppData\Roaming\npm\alm

The file path `C:\Users\kataras\AppData\Roaming\npm\alm` is actually a `bash` file not a `nodejs/javascript` file. 

![image](https://cloud.githubusercontent.com/assets/874898/14658677/18d727e4-06d9-11e6-96ea-7a60dc4dac02.png)

The file `C:\Users\kataras\AppData\Roaming\npm\node_modules\alm\bin\alm` is the nodejs file 

![image](https://cloud.githubusercontent.com/assets/874898/14658709/53cc14e0-06d9-11e6-846f-777c407b6657.png)

This is just how `npm install -g` works `¯\_(ツ)_/¯`

>  I will figure it myself, I am closing this issue sorry for your time spent

Absolutely no worries. Thanks for being an early adapter. Your early `npm` bug report was **invaluable** and probably saved me some future embarrassment :rose:

**Comment by kataras** [comment]
Yeah I know it didn't worked too... I tried with node ...server.js and again didn't worked I dont know what's whrong while 'tsc' is working well I can't find a solution

**Comment by basarat** [comment]
> I change the stderr to Iris stderr and there is an error now

Hmm. It shouldn't be `graceful-fs`. Something is injecting `graceful-fs` and replacing `fs` and its not me. 

FWIW I am calling this function: https://nodejs.org/api/process.html#process_process_chdir_directory (basicially changing the `cwd` ensures that relative paths are resolved correctly later on).

**Comment by kataras** [comment]
Yes you do that on the server, after argv...so I have to fork and remove these checks or should add a command line option only for this purpose? ( I understand that is useless for general purpose but it doesn't run otherwise..)

**Comment by basarat** [comment]
> Yes you do that on the server, after argv...so I have to fork and remove these checks or should add a command line option only for this purpose

Sorry I am unsure by what you mean.

Reading through the docs : https://github.com/isaacs/node-graceful-fs#global-patching something I am using is calling `gracefulify`. I'll try and remove that module or create an issue in the module repo or send them a PR.

**Comment by kataras** [comment]
I am making live editings on the comment, sorry next time I write new post, now I have an error that path must be string

**Comment by kataras** [comment]
@basarat  I think found what happens, the arguments are not passed as strings, on commandLine.js endsWith error, I convert the dir to the string rootDir = rootDir+"" and this error disappear, but after I have an error after:
```
TSCONFIG: C:/Users/kataras/Desktop/editor_example/scripts/true/tsconfig.json ( I dont know why true is there)
events.js:154
throw er; // Unhandlded 'error' event
```

Error: getaddrinfo ENOTFOUND ost 127.0.0.1 
    at errnoException (dns.js:26:10)...and so on

**Comment by basarat** [comment]
> I am making live editings on the comment, sorry next time I write new post, now I have an error that path must be string

I have checked it, there are two scenarios:

* Getting *two* inputs to `-d`. Here you will get the error "path must be a string".

This can happen if you pass `-d` *twice* e.g.: 

![image](https://cloud.githubusercontent.com/assets/874898/14660918/e75e0b60-06ec-11e6-96b4-afcd07f07e6a.png)

* Giving a directory that doesn't exist. Here you will get the error "No such file or directory"

As shown below: 

![image](https://cloud.githubusercontent.com/assets/874898/14660959/23d8a80c-06ed-11e6-9d8d-760cf9e7a66f.png)

**Comment by kataras** [comment]
On mine tests it shows Received [ True ] , I think arguments are not passed as strings

**Comment by kataras** [comment]
searching on the https://raw.githubusercontent.com/Microsoft/TypeScript/master/lib/tsc.js I found that they have a function named 'parseCommandLine' on line: 33988 , I think you should give a look on it, because tsc.js is working on me but alm command line arguments not passed correct as strings(or int or bool)

**Comment by basarat** [comment]
> I found that they have a function named 'parseCommandLine'

Thanks. But that function is specific to command line arguments for `tsc`. Our function is specific to `alm` + it uses `minimist` (a million downloads https://www.npmjs.com/package/minimist) which has `string` vs `boolean` support : https://github.com/alm-tools/alm/blob/2b41a1adcba61140eda3b45693e4397708aecc90/src/server/commandLine.ts#L28-L29

Can you reproduce the bug on manually writing the command line (instead of passing it through code)?

**Comment by kataras** [comment]
No no manually is working well, the problem is only through code, the weird is that tsc and nodemon is working via code

**Comment by kataras** [comment]
I tried on src/server/commandLine.js
```js
///....
function parseStrings(args) {
    var options = {};
    var i = 0;
    while (i < args.length) {
        var s = args[i];
        i++;
        if (s.charCodeAt(0) === 45) {
            s = s.slice(s.charCodeAt(1) === 45 ? 2 : 1).toLowerCase();
            switch (opt.type) {
            case "number":
                options[opt.name] = parseInt(args[i]);
                i++;
                break;
            case "boolean":
                options[opt.name] = true;
                break;
            case "string":
                options[opt.name] = args[i] || "";
                i++;
                break;
            }
        } else {
            console.log(s.charCodeAt(0))
        }
    }
    return options
}


exports.getOptions = utils.once(function () {
    var options = parseStrings(argv)
    options = {
        port: options.t || argv.t
        , dir: options.d || argv.d
        , open: options.o || argv.o
        , safe: options.safe || argv.safe
        , project: options.p || argv.p
        , init: options.i || argv.i
        , build: options.build || argv.build
        , filePaths: options.filePaths || []
        , host: options.h || argv.h
        , httpskey: options.httpskey || argv.httpskey
        , httpscert: options.httpscert || argv.httpscert
        , user: options.user || argv.user
        , pass: options.pass || argv.pass
    };

///....
```

now no errors with strings endsWith but : 

[!IMG](http://i63.tinypic.com/34h9ycx.png)

**Comment by kataras** [comment]
Ok it's working now port,user,pass are not passed correctly and it starts on port 4444 but the directory (-d) passed correcty and it runs without errors ( -host was the problem on the last screenshot should used --host)

**Comment by kataras** [comment]
this has solved the problem with the whrong type of arguments(?)
```js
//...
function parseStrings(opt) {
    var options = opt;
    for (var k in opt) {
        var s = opt[k]+"";
        if (opt.hasOwnProperty(k)) {
            if (s.charCodeAt(0) === 45) {

                if (typeof (opt[k]) == "number") {
                    options[k] = parseInt(opt[k]);

                } else if (typeof (opt[k]) == "boolean") {
                    options[k] = opt[k]
                } else if (typeof (opt[k]) == "string") {
                    options[k] = opt[k] || "";
                }

            }

        }
    }


    return options;
}


exports.getOptions = utils.once(function () {

    var options = {
        port: argv.t
        , dir: argv.d
        , open: argv.o
        , safe: argv.safe
        , project: argv.p
        , init: argv.i
        , build: argv.build
        , filePaths: []
        , host: argv.h
        , httpskey: argv.httpskey
        , httpscert: argv.httpscert
        , user: argv.user
        , pass: argv.pass
    };
    options = parseStrings(options)
//...

```

but it doesn't read all, now -d is working and alm started without problem:

![img2](http://tinypic.com/r/2gw9ob4/9)

but it starts on port 4444,  arguments --user, --pass and -t are ignored but -d is working now

**Comment by kataras** [comment]
src/server/disk/workingDir.js 
```js

//...
function setProjectRoot(rootDir) {
        // added 
	if (Object.prototype.toString.call(rootDir) === '[object Array]') {
		rootDir = rootDir[1]
	}else if (rootDir.indexOf(" ") !== -1) {
		rootDir = rootDir.split(" ")[1]
	}
       // end added
	
      projectRoot = fsu.consistentPath(rootDir);
      process.chdir(projectRoot);
}
exports.setProjectRoot = setProjectRoot;

//...

```

Now the error dissapear and alm started correctly but --host,--user,--pass and -t are ignored, only -d is passed correctly(;)

![img](http://i65.tinypic.com/2gw9ob4.jpg)

**Comment by kataras** [comment]
I edited only the js file, I don't want to pull a request for so little changes, so 

```js
//on alm/src/server/commandLine.js:31
//...
    var options = {
        port: argv.t
        , dir: argv.d
        , open: argv.o
        , safe: argv.safe
        , project: argv.p
        , init: argv.i
        , build: argv.build
        , filePaths: []
        , host: argv.h
        , httpskey: argv.httpskey
        , httpscert: argv.httpscert
        , user: argv.user
        , pass: argv.pass
    };

    for (var k in options) {
        var val = options[k]
        if (typeof (val) == "string") {
            var idxSpace = val.lastIndexOf(" ")
            if (idxSpace > 0) { // if has space inside it
                val = val.split(" ")[1]
            } else if (idxSpace === 0) { //if start's with space
                val = val.substring(1)
            }
            options[k] = val
        }

    }
        if (options.port && typeof(options.port) === "string") {// port is passed as string from external process/though code
        options.port = parseInt(options.port)
    }
//...

```


```js
//on alm/src/server/disk/workingDir.js:11 
//...
exports.getProjectRoot = getProjectRoot;
function setProjectRoot(rootDir) {
    // fix graceful-fs error when running by external process/code
	if (Object.prototype.toString.call(rootDir) === '[object Array]') {
		rootDir = rootDir[1]
	}else if (rootDir.indexOf(" ") !== -1) {
		rootDir = rootDir.split(" ")[1]
	}
    //

    projectRoot = fsu.consistentPath(rootDir);
    process.chdir(projectRoot);
}

//...
```
now the console.log(options), prints: 

```
{ port: '4545',
  dir: 'C:\\Users\\kataras\\Desktop\\editor_example\\scripts',
  open: false,
  safe: false,
  project: undefined,
  init: false,
  build: false,
  filePaths: [],
  host: '127.0.0.1',
  httpskey: undefined,
  httpscert: undefined,
  user: undefined,
  pass: undefined }

```

port is fixed via parseInt  later in commandLine.js , now the only problem is user and pass not passed as arguments

**Comment by basarat** [comment]
I just pushed a version `0.0.22` that will now error out if a command line argument was supposed to be with double dashes but a single dash was used (`--user` vs `-user`). 

<img width="953" alt="screen shot 2016-04-20 at 6 00 10 pm" src="https://cloud.githubusercontent.com/assets/874898/14667272/c3ea4f7e-0721-11e6-92e8-b9b6373161a1.png">

Seems like a common enough user error to protect against :rose:

**Comment by kataras** [comment]
If I pass double -- it doesn't takes that as arguments, this was the second problem:/

**Comment by kataras** [comment]
Also I recommend you to change the --user and --pass to one: --auth username:password (it can be an alias too ( -a ) )

**Comment by basarat** [comment]
> I recommend you to change the --user and --pass to one: --auth username:password (it can be an alias too ( -a ) ).

Agreed :rose: I'll change that and mention it here

**Comment by kataras** [comment]
these are the files I have to edit in order to work , you can see them https://github.com/iris-contrib/alm-files

**Comment by basarat** [comment]
> these are the files I have to edit in order to work

for `-a` or something else? I've just released `-a` before reading that source code : https://github.com/alm-tools/alm/commit/e86e9ef3db8ae1eab7df023fe3d0edff62330344 :rose:

**Comment by kataras** [comment]
for -a yes, it's ok now I just added alias for httpskey and httpscert (-k -c) I think you should add the changes I provide here https://github.com/alm-tools/alm/issues/60#issuecomment-212249998 ... now I have to make npm install -g alm and after make an installer from the iris-contrib github repo and copy files and all that... it will be easier just add these to the official alm package :P

**Comment by basarat** [comment]
Seeing code https://github.com/iris-contrib/alm-files/blob/7eeca74e8f1a7c3ac732cc26a0c9d467b438fda6/src/server/disk/workingDir.js#L13-L18 

are you sure its not because you are passing two `-d` i.e. `-d foo -d bar`? (as shown below): 

![](https://cloud.githubusercontent.com/assets/874898/14660918/e75e0b60-06ec-11e6-96b4-afcd07f07e6a.png)

**Comment by kataras** [comment]
Yes totally sure, I pass it only once, it is a problem no for you but from the package you are using to parse arguments...

**Comment by basarat** [comment]
I am just concerned about adding a symptomatic code fix without understanding the underlying cause. 

Did another test and it seems to work fine :-/ 

https://cloud.githubusercontent.com/assets/874898/14660918/e75e0b60-06ec-11e6-96b4-afcd07f07e6a.png

**Comment by kataras** [comment]
I don't understand, you telling me that the -d can be passed more than one and this is ok? I though we could have only one directory, this will change the things

**Comment by kataras** [comment]
No need to do anything else, thanks you, it's working now( for now) I hope that I can always understand your changes and update the nessecary files at the future releases :P

**Comment by basarat** [comment]
> you telling me that the -d can be passed more than one time and this is ok

No. I am saying the opposite. Basically I am worried that if I allow `-d` to be an array there might be an actually user error in the future and we siliently ignore it because we assume that providing -d twice is okay. 

> I hope that I can always understand your changes and update the nessecary files at the future releases

👍 Thanks :rose: 💯

**Comment by kataras** [comment]
At the code I don't allow the -d to passed as array, the oposite, if it's an array or has space , then take only the second path as the -d's value :P me thanks <3

**Comment by basarat** [comment]
Sorry to bother you again, but I've been thinking about this. Can you put a `console.log(process.argv.slice(2));` in `commandLine.ts`: 

![image](https://cloud.githubusercontent.com/assets/874898/14739634/28bcea82-08cc-11e6-9783-414c132d0e58.png)

I suspect your output will **not** be an array like mine: 

![image](https://cloud.githubusercontent.com/assets/874898/14739644/4301d830-08cc-11e6-89cb-af8e27f82999.png)

If its not an array I might have a better fix :rose:

**Comment by basarat** [comment]
@kataras ^ :rose:

**Comment by kataras** [comment]
Hello, I just woke up, no problem you don't bother me, the oposite !
(Unfortunately?) It's an array, here's the output:

[ '-a username:password',
  '-h 127.0.0.1',
  '-t 4545',
  '-d C:\\Users\\kataras\\Desktop\\editor_example\\scripts' ]
DASHBOARD: http://localhost:4545
TSCONFIG: All Good! C:/Users/kataras/Desktop/editor_example/scripts/tsconfig.json
[TSC] Started Initial Error Analysis: C:/Users/kataras/Desktop/editor_example/scripts/tsconfig.json
[TSC] Error Analysis Duration: 1s
[TSC] FileCount: 1  Errors: 0
[EMIT] Starting emit
[EMIT] Completed emit

**Comment by basarat** [comment]
> no comma separated between the name of the arguments and the values on mine input so it's not an array

Indeed. This would cause the parsing to fail. Basically *consoles* separate the *args* by `space` (unless they are inside a quote). But when we as developers are calling an executable in *code* using a lower level API then we are responsible of making that deliniation. 

In your case, can you share the code that spawns alm? It should be sending two args (`-t` and `4545`) instead of one (`-t 4545`). :rose:

**Comment by kataras** [comment]
Ok I understood, I converted the code and now is working!! I dont understand why I had them as one parameter  ( '- t 4545', '-d /path/to') on my other implemenatation  for tsc compiler I had them separated lol. Maybe the first I thought that this should be the error and I changed it to pass name and value together as one. Thanks you now is working without copying the files after installation!! It was so simple again and I make it so hard... xD

**Comment by basarat** [comment]
No worries. Thanks for your patience and persistence 🌹❤️

**Comment by kataras** [comment]
Both of us have pattience  ahah, thanks you man nice job!
