### ISSUE TITLE
Error: ENOSPC: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by FrancescoBorzi** [alm-tools/alm#651]
I've just tried to use alm for the first time but I when I try to run it I get:

> Error: ENOSPC: System limit for number of file watchers reached

**Comment by basarat** [comment]
I need to add a deprecation notice. I've moved to VSCode for my day to day :rose:

**Comment by FrancescoBorzi** [comment]
@basarat does it mean that alm is no longer supported/developed ?

**Comment by basarat** [comment]
Yes :rose:
