### ISSUE TITLE
Is this normal? (See pic)

### ISSUE THREAD

**Issue by sigmasoldi3r** [alm-tools/alm#657]
Aside from the project not being maintained, I've seen this:

![image](https://user-images.githubusercontent.com/13834659/88453293-e8255180-ce65-11ea-939f-7e931215620b.png)

That doesn't seem right... It is a partner, or someone had that slip in though a PR?

**Comment by basarat** [comment]
I let the domain `alm.tools` expire as https://alm-tools.github.io/ is free and good enough as a snapshot.

Sadly someone decided to buy it and use it for spam 😢. Just one more reason that I *don't* buy domains for OSS projects anymore :rose:

**Comment by djmaze** [comment]
Then you should at least change the website link in the README to https://alm-tools.github.io/ so people do not get scammed.

**Comment by basarat** [comment]
Done :rose:
