### ISSUE TITLE
allowJS

### ISSUE THREAD

**Issue by basarat** [alm-tools/alm#75]
The **KEY** :key:  motivation of this project is to convince people that TypeScript can be just as simple as JavaScript. There are a lot of JavaScript projects out there and right now they are being informed that they need to use TypeScript. But then all of a sudden they now have to setup a transpiler + editor and there isn't a clear step by step error free migration path.

The goal of this project is to provide them with a single npm install that gets them 80% of the way and they just focus on doing the migration. Of course this is not an easy task if they have a lot of JS files that need migrating. So we need to provide first class support for allowJS. This is why I took next week off :rose:

Giving error panel filtering : https://github.com/alm-tools/alm/issues/71 was actually motivated by the same reasons :rose:

**Comment by basarat** [comment]
Sample :rose:

![image](https://cloud.githubusercontent.com/assets/874898/15271473/1f76e58e-1a8f-11e6-82ed-24d1767946c2.png)

**Comment by afaayerhan** [comment]
sequelizejs
