### ISSUE TITLE
Class Diagram View

### ISSUE THREAD

**Issue by basarat** [alm-tools/alm#84]
Create a live updating class diagram view

**Comment by basarat** [comment]
Done ! :rose: 

Screenshots: 

![override](https://cloud.githubusercontent.com/assets/874898/15416106/23daabec-1e8b-11e6-9808-bc54e8319aaf.png)

![live](https://cloud.githubusercontent.com/assets/874898/15416111/3598ab36-1e8b-11e6-8b8c-16962bb9bd82.gif)


# Docs

https://basarat.gitbooks.io/alm/content/features/uml.html

**Comment by GBatault** [comment]
Is-it possible to generate a global diagram for aller classes , with relationship between classes ?

**Comment by basarat** [comment]
@gbatault The code to get the data is easy for me. The code to draw I will have to research 🌹

**Comment by GBatault** [comment]
@basarat OK tank you ! An other possible feature : a way to export the diagram into a static HTML file (or folder) (I know that TypeDoc as an export function)

**Comment by basarat** [comment]
> An other possible feature : a way to export the diagram into a static HTML file (or folder) (I know that TypeDoc as an export function)

I've thought about it. The key complexity is click actions ... we need to open the file on e.g. github for html files ? In app its simply opening the file from disk into the IDE. Punting on the static html portion for now :rose:

**Comment by GBatault** [comment]
OK, I see. My need is pretty simple : get a full TypeScript class diagram to document my application (wich people can access throw a directory : It meens no IDE or NodeJs server.

**Comment by basarat** [comment]
> The code to draw I will have to research

The code to draw is actually simple if we just think about the boxes (individual classes) and lines between them. However the code to organize such boxes can get complex and don't see a good OSS solution out there right now. So closing as its too much work for me to target ... just yet :rose:
