### ISSUE TITLE
How to use it with angular 2 projects

### ISSUE THREAD

**Issue by Alexisvt** [alm-tools/alm#88]
Hi @basarat, first thank you for your excellent work on this IDE, it looks promising! I like it a lot and for that reason I want to use right away with some projects that I have with angular2, but I'm having some issues, the editor tell me that I can't give intellisense since some of my file are not part of the typescript project, I don't know what I'm doing wrong.
I'm using the angular-cli for generate all the files. Here a paste a screenshot of problem

![image](https://cloud.githubusercontent.com/assets/7120647/15431555/aac469f0-1e67-11e6-9a9a-95d14169c1e3.png)

As you can see the folder that contains all the typescript file is at **src**, I'm opening **alm** editor in that folder (it also contains the tsconfig.json file), but I'm seeing this error, thanks for your kind help :smile:

**Comment by Alexisvt** [comment]
Hi again I think I discovered the problem, I went to tsconfig file and I'm seeing that angular-cli is configuring the TS project to only watch two files, Is this causing the problem, right? :cry: 

![image](https://cloud.githubusercontent.com/assets/7120647/15431820/c7e1c928-1e68-11e6-95f2-99dd1be70e85.png)

**Comment by basarat** [comment]
I think `angular-cli` generates a file structure that has *multiple* `tsconfig.json` files. ALM just selects the first one it finds (with sane things around command line selection / last session project etc). 

You can change the project you are working on by just using the project selector https://basarat.gitbooks.io/alm/content/features/omni-search.html#project-search :rose:

![](https://raw.githubusercontent.com/alm-tools/alm-tools.github.io/master/screens/projectSearch.gif)

Let me know if this does not fix it :rose:

**Comment by basarat** [comment]
Since you managed to figure out that you need to click `tsconfig.json` we will now show a help for other people about *changing active project* :rose: 

![clickontsconfig](https://cloud.githubusercontent.com/assets/874898/15440172/5c667bc6-1f17-11e6-9d70-1b8e44407b9c.gif)
