### ISSUE TITLE
No create folder action! Feature needed in case that it doesn't exists!

### ISSUE THREAD

**Issue by Alexisvt** [alm-tools/alm#98]
Is there a way to create an empty folder using the `file tree` panel? I can't find it anywhere :cry: 

![image](https://cloud.githubusercontent.com/assets/7120647/15456071/c63e89b0-2022-11e6-8787-566538ca56f5.png)

**Comment by Alexisvt** [comment]
I think I got again the workaround! The step is pretty straightforward but again the option it's needed!

If i press the `a` action in the folder tree I can type at the same time the folder name and the file name:

![almeditor](https://cloud.githubusercontent.com/assets/7120647/15456165/69172050-2025-11e6-9958-dd2d8c65557d.gif)

Again I think that will be good to have that option, so pleaseee can you add it for us...? :stuck_out_tongue_closed_eyes:

**Comment by basarat** [comment]
> Again I think that will be good to have that option, so pleaseee can you add it for us...

Will do. Atom tree view shortcut is `Shift + A` so will add the same :rose:

**Comment by basarat** [comment]
One minor (big) issue. We don't list empty folders! So even though the folder is created we would not list it. Will fix that later so leaving it as open for now :rose:

* [ ] Todo : list empty folders

**Comment by basarat** [comment]
Released with `0.0.61` :rose:
