### ISSUE TITLE
Invalid error on creating a file within a NativeScript project

### ISSUE THREAD

**Issue by Alexisvt** [alm-tools/alm#99]
Hi @basarat Im receiving an error when I try to create a xml file with **alm** tool within a Nativescript project. I'm receiving this error everytime that I tried to create a simple xml file.

This is the error that Im seeing on alm tool console:

```cmd
$ alm -o
DASHBOARD: http://localhost:4444
TSCONFIG: All Good! C:/NativeScriptRepo/atalaya/tsconfig.json
[TSC] Started Initial Error Analysis: C:/NativeScriptRepo/atalaya/tsconfig.json
[TSC] Error Analysis Duration: 3s
[TSC] FileCount: 115  Errors: 3
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, lstat 'C:\NativeScriptRepo\atalaya\platforms\android\src\main\assets\app\tns_modules\tns-core-modules\ui\builder'
    at Error (native)
 ts worker restarting. Don't know why it stopped with code: 1
```

And I will paste here as well the error that Im seeing on the nativescript console to give you more information:

```cmd
Found peer TypeScript 1.8.10
4:51:12 PM - Compilation complete. Watching for file changes.

Executing before-prepare hook from C:\NativeScriptRepo\atalaya\hooks\before-prepare\nativescript-dev-typescript.js
C:\NativeScriptRepo\atalaya\app\views\sample-view.xml has syntax errors.
error
invalid document source
@#[line:0,col:undefined]

Project successfully prepared
Transferring project files...
Successfully transferred all project files.
Applying changes...
Successfully synced application org.nativescript.atalaya on device 192.168.1.101:5555.
Executing before-prepare hook from C:\NativeScriptRepo\atalaya\hooks\before-prepare\nativescript-dev-typescript.js
C:\NativeScriptRepo\atalaya\app\views\sample-view.xml has syntax errors.
error
invalid document source
@#[line:0,col:undefined]

Project successfully prepared
Transferring project files...
Unable to sync files. Error is: EISDIR: illegal operation on a directory, read
```

**Comment by Alexisvt** [comment]
Another detail is that when this happen (when I create the file in the nativescript project which is livesync with the emulator ) everything stop to work. I need to stop alm tool and also nativescript cli. After doing that I can't use alm tool anymore because nativescript cli complains about it showing again the error that I pasted before!

**Comment by basarat** [comment]
> Unable to sync files. Error is: EISDIR: illegal operation on a directory, read

^ this is an error reported by `tns` (native script cli) right?

**Comment by Alexisvt** [comment]
Yes! the last one! the first one is alm tool

**Comment by basarat** [comment]
>  ts worker restarting. Don't know why it stopped with code: 1

The worker name is probably wrong. I've pushed a version that will now show the file name `0.0.60`. I suspect its the file listing worker. I don't think we can prevent it from crashing (unless we know the root cause) but we should recover gracefully. Please provide a new if possible :rose: 

That said, I'll have to look at this later tonight (going offline for now) :rose:

**Comment by Alexisvt** [comment]
Thanks! I will test it! right away and I will give you more info! regards :+1:

**Comment by Alexisvt** [comment]
@basarat the same behavior is present on vscode so I think this is something on nativescript, about the error that we saw on the nativescript cli was because the xml file wasn't valid as soon as I add valid xml code there the app run well (alm tool and vs code). Both did the same behavior on nativescript cli and both need to restart nativescript cli to make it work again.

**Comment by basarat** [comment]
Quick question: Does alm recover gracefully or you need to manually restart? If alm needs a manual restart to do *its job* we can reopen this bug and work towards figuring it out. If its just nativescript then this can remain closed :rose:

**Comment by basarat** [comment]
Quick question: Does alm recover gracefully or you need to manually restart? If alm needs a manual restart to do *its job* we can reopen this bug and work towards figuring it out. If its just nativescript then this can remain closed :rose:
